## Wallpaper config

# Inbuilt display
wallpaper {
    monitor = eDP-1
    path = ~/.config/hyprwallpapers/hypr.png
    fit_mode = cover
}

# External display
wallpaper {
    monitor = HDMI-A-1
    path = ~/.config/hyprwallpapers/anime1.png
    fit_mode = cover
}

# Extra settings
splash = false
ipc = off
